### ISSUE TITLE
Running author function without proper preparation.

### ISSUE THREAD

**Issue by yuki3** [WICG/animation-worklet#94]
["create a new animator instance"](https://wicg.github.io/animation-worklet/#create-a-new-animator-instance) step 6 invokes an arbitrary author function through Construct without performing ["prepare to run script"](https://html.spec.whatwg.org/multipage/webappapis.html#prepare-to-run-script) nor ["prepare to run a callback"](https://html.spec.whatwg.org/multipage/webappapis.html#prepare-to-run-a-callback).

From the beginning, `animatorCtor` is a callback function, and callback function is not designed to be used as a constructor IIUC.  ["invoke"](https://heycam.github.io/webidl/#es-invoking-callback-functions) algorithm is expected to be used instead, where "prepare to run script" and "prepare to run a callback" are supported.

By the way, ["run animators"](https://wicg.github.io/animation-worklet/#run-animators) looks strange, too.  It pretty much looks like [callback interface](https://heycam.github.io/webidl/#es-user-objects), but it's actually defined as a [callback function](https://heycam.github.io/webidl/#idl-callback-functions) and behaves differently.  The difference looks to me an unnecessary confusion.

From a point of view of Web IDL, it would be natural to define `animatorCtor` as a generator (not a constructor) that returns a new instance of callback interface that supports `animate` operation.  Then, we can [call a user object's operation](https://heycam.github.io/webidl/#es-invoking-callback-functions) with the instance and operation name "animate".  Or, we can define `animatorCtor` as a generator that returns a callback function if callback function is preferred.

**Comment by majido** [comment]
Thanks for the detailed feedback. 

I agree that animatorCtor should not really be a callback.

### ecma+ WebIDL route - PaintWorklet route
Here is how [Paint Worklet spec](https://drafts.css-houdini.org/css-paint-api/#registering-custom-paint) handles a similar case: 
-  `paintCtor` is a function that has to pass  [`IsConstructor()`](https://tc39.github.io/ecma262/#sec-isconstructor) test. So effectively a constructor function.
- Access paintCtor's prototype via `Get(paintCtor, "prototype")` and expect it to be an object.
- Access paint function via `Get(prototype, "paint")` and it is a ecma [`function`](https://tc39.github.io/ecma262/#sec-terms-and-definitions-function) 
- When necessary instantiate a paint instance by calling paintCtor as a constructor `Construct(paintCtor).`

All of this uses the types and operations from ecma. But when it come to actually invoking the paint function, it is using the webidl [`Invoke`](https://heycam.github.io/webidl/#invoke-a-callback-function) algorithm on the paint function.

### WebIDL only route - your suggestion route

You suggestion only relied on web idl types and operations. Here is what I think it amounts to:
- `animatorCtor` becomes a callback function (generator?) which we can be constructed.
- `animate` becomes an operation on that interface.
- on registration we expect to receive an function callback that will be used to construct new instances.
- on animation:
   1. Construct a new instance of Animator by using [construct a callback](https://heycam.github.io/webidl/#construct-a-callback-function) operation. The result should be an object that implement the Animator callback interface.
   2. Call the `animate` operation of the animator instance using []()

```webidl
[Constructor]
callback interface Animator {
   animate(double currentTime, AnimationEffect effect);
}

[Global=AnimationWorklet]
interface AnimationWorkletGlobalScope : WorkletGlobalScope {
    void registerAnimator(DOMString name, Animator animatorCtor);
};
```

One problem I found however is that [according to webidl](https://heycam.github.io/webidl/#Constructor) we cannot construct a callback interface.  
> "The [Constructor] extended attribute must not be used on a callback interface."


### Summary
I believe your suggestion to use only webidl type is clean and makes sense if we can address the construction issue above. 

On the other hand I like to be consistent with PaintWorklet if possible. @bfgeek  do you know if there is any reason why PaintWorklet is using ecma types instead of webidl.

**Comment by yuki3** [comment]
Let me clarify my point on this issue:  The current "CSS Animation Worklet API" spec is **_inconsistent_** with HTML and Web IDL specs.  Calling an author function without "prepare to run script" and "prepare to run a callback" _conflicts_ with HTML spec.  So, this is not a problem of cleanness.  The problem is much more severe.

[CSS Painting API Level 1](https://drafts.css-houdini.org/css-paint-api/) has the same issue.  It conflicts with HTML spec, too.

In short, we are not allowed to call ECMAScript's [Construct](https://tc39.github.io/ecma262/#sec-construct) (unless we perform "prepare to run script" and "prepare to run a callback").

**ECMAScript + Web IDL route**
It's difficult to be consistent with other web specs, such as DOM and HTML, if we're going to directly use ECMAScript spec.  It's pretty easy to conflict with other web specs like this issue.  Also it's fragile against future changes on other web specs.

**Web IDL only route**
There seems a confusion.  One of my suggestions is the following in Web IDL.

```
// Animator is defined as a callback interface.
//
// No need of [Constructor].
callback interface Animator {
  animate(double currentTime, AnimationEffect effect);
}

// AnimatorConstructor is defined as a callback **function**.
//
// Given a callback function animCtor as an instance of AnimatorConstructor,
// an invocation of animCtor() returns an instance of Animator.
//   animator = animCtor();
// where animator is an instance of Animator.
callback AnimatorConstructor = Animator ();

[Global=AnimationWorklet]
interface AnimationWorkletGlobalScope : WorkletGlobalScope {
    void registerAnimator(DOMString name, AnimatorConstructor animatorCtor);
};
```

There are many other options, so I'm not insisting on this way.

**Comment by majido** [comment]
@yuki3 We took a stab at correcting the issue. Please let me know if this addresses your original concern or there are still areas we can improve here. 

Here is the change summary:

- Use VoidFunction type for constructor, and Function type for animate and destroy callbacks.
- Use convert algorithm to convert incoming values to proper types upon registration
- Use invoke/construct algorithms to call or construct. This ensure the proper setup in place which addresses the original reported issue.

This follows the resolutions agreed for paint worklet which basically caches the appropriate function instances at registration time and invokes/construct them when necessary but now we are consistent
with the webidl type and algorithm usage.

**Comment by yuki3** [comment]
I'm now expecting that [the way of custom elements](https://html.spec.whatwg.org/multipage/custom-elements.html#element-definition) will be a standard way, and hopefully the algorithm should be defined in Web IDL so that it's easy for other web standards to follow it.

And my understanding is that CSS Animation Worklet is going to follow the way of custom elements, and I'm pretty happy with it.  :)

Overall, the change looks good, but I see one thing strange.  `VoidFunction`'s return type is type `void`, but constructor is expected to return the created object.  In case of custom elements, [CustomElementConstructor](https://html.spec.whatwg.org/multipage/custom-elements.html#customelementconstructor) returns `any` taking no argument.

If you don't like defining your own constructor type, `Function`, that returns `any`, is a better match than `VoidFunction`.
